menu:
    Blog: /
    Archive: /archives/

menulink:
    About: https://i.xavierwah.xyz
    GitHub: https://github.com/Shelter-Studio

favicon: /favicon.ico
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2021
